### ISSUE TITLE
Da passt was nicht

### ISSUE THREAD

**Issue by DaNeubi** [SachsKaylee/next-offline-example#1]
Jesus hilf mir

**Comment by SachsKaylee** [comment]
:(
Da passt in der Tat was nicht, die Repo dient auch dazu einen Bug zu melden. :)

**Comment by DaNeubi** [comment]
Ich nix Bug gefunden :O

**Comment by DaNeubi** [comment]
Hab den Fehler gefunden, da war keiner :O
Du hast dir wohl nich mal die Mühe gemacht um Bugs zu Impleementieren, dass andere die dann finden und melden können.... :(
